spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: lomofu
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
        #指定命名空间
        #namespace: 172f034e-cf81-4158-b84a-5a7613ee4fac
        #集群
        #cluster-name: NewYork
        #元数据
        metadata:
          version: 1.0
  application:
    name: user-center


server:
  port: 8085
