spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: lomofu
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
        #cluster-name: NewYork
        metadata:
          version: 1.0
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
    name: content-center

server:
  port: 8081

ribbon:
  eager-load: true
  clients: user-center

#ribbon负载均衡规则
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.lomofu.contentcenter.configuration.NacosWeihtedRule
logging:
  level:
    com.lomofu.contentcenter.httpclient.UserCenterFeignClient: debug
#feign配置
feign:
  client:
    config:
      default:
        loggerLevel: full
  #开启apache httpclinet 而不是默认的urlconnection
  httpclient:
    enabled: true
    #最大连接数量
    max-connections: 200
    #单个路径的最大连接数
    max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'
