spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: lomofu
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
  application:
    name: content-center

server:
  port: 8081

ribbon:
  eager-load: true
  clients: user-center

#ribbon负载均衡规则
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.lomofu.contentcenter.configuration.NacosWeihtedRule

